/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { useForm } from "react-hook-form";
import Icon from "~/components/Icon";

const ListingView: NextPage = () => {
	const router = useRouter();
	const { register, handleSubmit, reset } = useForm<{ message: string }>();

	const listing = api.listings.get.useQuery(
		{
			listingId: router.query.id as string,
		},
		{
			enabled: !!router.query.id,
		}
	);
	const user = useUser();

	const sendMessage = api.listings.sendMessage.useMutation();

	const listingItem = listing.data;

	if (!listingItem) {
		return null;
	}

	return (
		<>
			<Head>
				<title>{listingItem.name}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col gap-6" style={{ background: '#efefef', padding: '40px 0px' }}>
				<div className="container mx-auto flex flex-row gap-6" style={{ alignItems: 'self-start' }}>
					<div className="card saas-details-wrapper">
						<div className="navigation-wrapper flex w-100 justify-between">
							<div className="left flex left">
								<div className="icon-wrapper">
									<Icon icon='go_back' />
								</div>
								<span>312 people viewed this listing</span>
							</div>

							<div className="right flex justify-between">
								<div className="wishList">
									<div className="icon-wrapper">
										<Icon icon='wishlist' />
									</div>
								</div>
								<div className="icon-wrapper">
									<Icon icon='notifications_on' />
								</div>
							</div>
						</div>

						<div className="divider"></div>

						<div className="card-header">
							<div className="left">
								<div className="category-wrapper">
									<Icon icon='saas_icon' />
								</div>
								<div className="product-name">
									<div className="title">
										{listingItem.name}
									</div>
									<span className="created-at">Listed at 27.04.2023</span>
								</div>
							</div>
							<div className="right flex location-wrapper">
								<Icon icon='location' />
								<span>United Kingdom</span>
							</div>
						</div>

						<div className="description-wrapper">
							{listingItem.description}
						</div>

						<div className="divider"></div>

						<div className="kpis">
							<div className="kpi">
								<span className="muted-label">TTM PROFIT</span>
								<p>$120k</p>
							</div>
							<div className="kpi">
								<span className="muted-label">TTM REVENUE</span>
								<p>$127k</p>
							</div>
							<div className="kpi">
								<span className="muted-label">ASKING PRICE</span>
								<p>$800k</p>
							</div>
							<div className="kpi">
								<span className="muted-label">TEAM SIZE</span>
								<p>3</p>
							</div>
							<div className="kpi">
								<span className="muted-label">DATE FOUNDED</span>
								<p>27.01.2021</p>
							</div>
						</div>

						<div className="divider"></div>

						<div className="section">
							<h1 className="heading-text">Company Overview</h1>

							<div className="muted-label">Description</div>
							<p className='paragraph'>{listingItem.description}</p>

							<div className="muted-label">Tech Stack</div>
							<p className='paragraph'>Next.js, Stripe, Replicate, Tailwind and Vercel</p>

							<div className="muted-label">Business Model</div>
							<p className="paragraph">B2C £9 for 25 credits, £19.00 for 100 credits and £29.00 for 200 credits/</p>

							<div className="muted-label">Competitors</div>
							<p className="paragraph">https://www.fotor.com/features/ai-landscape-generator/</p>

							<div className="muted-label">Growth opportunity</div>
							<div className="list">
								<p className="paragraph list-item">Do more marketing/</p>
								<p className="paragraph list-item">Add more styles/</p>
								<p className="paragraph list-item">Expand to other areas of home renovation/</p>
							</div>

							<div className="muted-label">Assets</div>
							<div className="list">
								<p className="paragraph list-item">Codebase and IP/</p>
								<p className="paragraph list-item">Website/</p>
								<p className="paragraph list-item">Domain/</p>
								<p className="paragraph list-item">Brand/</p>
							</div>
						</div>

						<div className="divider"></div>

						<div className="section">
							<h1 className="heading-text">Aquisition details</h1>

							<div className="muted-label">Reason selling</div>
							<p className='paragraph'>I am not good with marketing and have started working on other projects.</p>

							<div className="muted-label">Financing</div>
							<p className='paragraph'>100% Bootstrapped. </p>
						</div>
					</div>

					<div style={{ width: '40%' }}>

						<div className="metrics-overview-wrapper card no-padding-x">
							<h1 className="heading-text">Quick overview</h1>
							<div className="divider"></div>

							<div className="images-wrapper">
								<div className="image">
									<img src="https://upcdn.io/FW25bBB/image/content/app_screens/db79e46a-1b8a-41fb-9dc4-649fd95ac42f.png?f=webp&w=1920&q=85&fit=shrink-cover&extend-bottom=120&image=%2Fwatermark%2Fdbc9efc5-2c2a-439a-915a-853ca8c242a2&gravity=bottom" alt="" />
								</div>
							</div>
						</div>

						<div className="metrics-overview-wrapper card">
							<h1 className="heading-text">Customers overview</h1>
							<div className="divider"></div>

							<div className="flex kpi-container-wrapper">
								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='customers' />
									</div>
									<span>Customers</span>
									<p>10-100</p>
								</div>
								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='recurring' />
									</div>
									<span>Annual recurring revenue</span>
									<p>328k</p>
								</div>

								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='percent' />
									</div>
									<span>Annual growth rate</span>
									<p>2%</p>
								</div>
							</div>
						</div>

						<div className="metrics-overview-wrapper card">
							<h1 className="heading-text">Financials snapshot</h1>
							<div className="divider"></div>

							<div className="flex kpi-container-wrapper">
								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='cash' />
									</div>
									<span>TTM gross revenue</span>
									<p>$0</p>
								</div>
								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='revenue' />
									</div>
									<span>TTM net profit</span>
									<p>$0</p>
								</div>

								<div className="kpi-wrapper">
									<div className="icon">
										<Icon icon='calendar' />
									</div>
									<span>Last months net profit</span>
									<p>$0</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default ListingView;
