/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { useForm } from "react-hook-form";
import Icon from "~/components/Icon";
import InvisibleNavbar from "~/components/InvisibleNavbar";
import Link from "next/link";
import moment from 'moment'

const ListingView: NextPage = () => {
	const router = useRouter();
	const { register, handleSubmit, reset } = useForm<{ message: string }>();

	const listing = api.listings.get.useQuery(
		{
			listingId: router.query.id as string,
		},
		{
			enabled: !!router.query.id,
		}
	);
	const user = useUser();

	const sendMessage = api.listings.sendMessage.useMutation();

	const listingItem = listing.data;

	if (!listingItem) {
		return null;
	}

	return (
		<>
			<Head>
				<title>{listingItem.name}</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div style={{ width: '100%'}}>
                <InvisibleNavbar />
                
				<main className="container mx-auto flex min-h-screen flex-col gap-6">
					<div className="container mx-auto flex flex-row gap-6" style={{ alignItems: 'self-start' }}>
						<div className="card saas-details-wrapper"  style={{ border: '1px solid #efefef' }}>
							<div className="navigation-wrapper flex w-100 justify-between">
								<div className="left flex left">
									<Link href="/browse">
										<div className="icon-wrapper">
											<Icon icon='go_back' />
										</div>
									</Link>
									<span>312 people viewed this listing</span>
								</div>

								<div className="right flex justify-between">
									<div className="wishList">
										<div className="icon-wrapper">
											<Icon icon='wishlist' />
										</div>
									</div>
									<div className="icon-wrapper">
										<Icon icon='notifications_on' />
									</div>
								</div>
							</div>

							<div className="divider"></div>

							<div className="card-header">
								<div className="left">
									<div className="category-wrapper">
										<Icon icon='saas_icon' />
									</div>
									<div className="product-name">
										<div className="title">
											{listingItem.name}
										</div>
										<span className="created-at">Listed at {moment(listingItem?.createdAt).format()}</span>
									</div>
								</div>
								<div className="right flex location-wrapper">
									<Icon icon='location' />
									<span>{listingItem.location}</span>
								</div>
							</div>

							<div className="description-wrapper">
								{listingItem.description}
							</div>

							<div className="divider"></div>

							<div className="kpis">
								<div className="kpi">
									<span className="muted-label">TTM PROFIT</span>
									<p>${listingItem.ttm_profit}</p>
								</div>
								<div className="kpi">
									<span className="muted-label">TTM REVENUE</span>
									<p>${listingItem.ttm_revenue}</p>
								</div>
								<div className="kpi">
									<span className="muted-label">ASKING PRICE</span>
									<p>${listingItem.price}</p>
								</div>
								<div className="kpi">
									<span className="muted-label">TEAM SIZE</span>
									<p>{listingItem.team_size}</p>
								</div>
								<div className="kpi">
									<span className="muted-label">DATE FOUNDED</span>
									<p>{moment(listingItem.date_founded).format()}</p>
								</div>
							</div>

							<div className="divider"></div>

							<div className="section">
								<h1 className="heading-text">Company Overview</h1>

								<div className="muted-label">Description</div>
								<p className='paragraph'>{listingItem.description}</p>

								<div className="muted-label">Tech Stack</div>
								<p className='paragraph'>{listingItem.tech_stack.join(', ')}</p>

								<div className="muted-label">Business Model</div>
								<p className="paragraph">{listingItem.business_model}</p>

								<div className="muted-label">Competitors</div>
								<p className="paragraph">{listingItem.competitors.join(', ')}</p>

								<div className="muted-label">Growth opportunity</div>
								<div className="list">
									<p className="paragraph list-item">{listingItem.growth_opportunity}/</p>
									{/* <p className="paragraph list-item">Add more styles/</p> */}
									{/* <p className="paragraph list-item">Expand to other areas of home renovation/</p> */}
								</div>

								<div className="muted-label">Assets</div>
								<div className="list">
									{listingItem.assets.map(asset => <p key={asset} className="paragraph list-item">{asset}/</p>)}
								</div>
							</div>

							<div className="divider"></div>

							<div className="section">
								<h1 className="heading-text">Aquisition details</h1>

								<div className="muted-label">Reason selling</div>
								<p className='paragraph'>{listingItem.reason_selling}</p>

								<div className="muted-label">Financing</div>
								<p className='paragraph'>{listingItem.financing}</p>
							</div>
						</div>

						<div style={{ width: '40%', border: '1px solid #efefef'}}>
								<div className="metrics-overview-wrapper card no-padding-x">
								<h1 className="heading-text">Quick overview</h1>
								<div className="divider"></div>

								<div className="images-wrapper">
									<div className="image">
										<img src="https://upcdn.io/FW25bBB/image/content/app_screens/db79e46a-1b8a-41fb-9dc4-649fd95ac42f.png?f=webp&w=1920&q=85&fit=shrink-cover&extend-bottom=120&image=%2Fwatermark%2Fdbc9efc5-2c2a-439a-915a-853ca8c242a2&gravity=bottom" alt="" />
									</div>
								</div>
							</div>

							<div className="metrics-overview-wrapper card">
								<h1 className="heading-text">Customers overview</h1>
								<div className="divider"></div>

								<div className="flex kpi-container-wrapper">
									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='customers' />
										</div>
										<span>Customers</span>
										<p>10-100</p>
									</div>
									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='recurring' />
										</div>
										<span>Annual recurring revenue</span>
										<p>328k</p>
									</div>

									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='percent' />
										</div>
										<span>Annual growth rate</span>
										<p>2%</p>
									</div>
								</div>
							</div>

							<div className="metrics-overview-wrapper card">
								<h1 className="heading-text">Financials snapshot</h1>
								<div className="divider"></div>

								<div className="flex kpi-container-wrapper">
									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='cash' />
										</div>
										<span>TTM gross revenue</span>
										<p>$0</p>
									</div>
									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='revenue' />
										</div>
										<span>TTM net profit</span>
										<p>$0</p>
									</div>

									<div className="kpi-wrapper">
										<div className="icon">
											<Icon icon='calendar' />
										</div>
										<span>Last months net profit</span>
										<p>$0</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</main>
            </div>

		</>
	);
};

export default ListingView;
