import { type Listing } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api } from "~/utils/api";
import LandingPage from '~/components/homepage/LandingPage'

const Home: NextPage = () => {
	const listings = api.listings.list.useQuery();

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<LandingPage></LandingPage>
		</>
	);
};

export default Home;
