import moment from "moment";
import Head from "next/head";
import Link from "next/link";
import { type NextPage } from "next";
import { type Listing } from "@prisma/client";

import { api } from "~/utils/api";

import Icon from "~/components/Icon";
import { useRouter } from 'next/router';
import { useEffect } from "react";

const ListedProduct = ({ listing }: { listing: Listing }) => {
	const router = useRouter();

	const formatNumber = (num: number): string => {
		if (!num) return num.toString();
		if (num >= 1000) {
			const suffixes = ["", "k", "M", "G", "T"];
			const magnitude = Math.floor(Math.log10(num) / 3);
			const roundedNum = (num / Math.pow(1000, magnitude)).toFixed(1);
			return `${roundedNum}${suffixes[magnitude]}`;
		}
		return num.toString();
	}

	const addQueryParam = (q: string) => {
		const currentPathname = router.pathname;

		router.push({
			pathname: currentPathname,
			query: { chatId: q },
		}, undefined, { shallow: true });
	};

	const openChat = () => {
		addQueryParam(listing.id)
	}

	return (
		<div className="product-card mb-4" onClick={openChat}>

			<div className="messages-notification-wrapper">
				4
			</div>

			<div className="card-header">
				<div className="left">
					<div className="category-wrapper">
						<Icon icon='saas_icon' />
					</div>
					<div className="product-name">
						<div className="title">
							{listing.name}
						</div>
						<span className="created-at">Listed {moment(listing.createdAt).fromNow()}</span>
					</div>
				</div>
				<div className="right gap-2">
					<div className="d-block">
						<div className="label" style={{ marginTop: 0 }}>ASKING PRICE</div>
						<span className="value">${formatNumber(listing.price)}</span>
					</div>

					<div className="d-block" style={{ height: '62.5px' }}>
						<div className="label" style={{ marginBottom: '8px', marginTop: '11px' }}>SAVES</div>
						<div className="d-flex" style={{ alignItems: 'center', columnGap: '4px' }}>
							<Icon icon='wishlist' size='xs' />
							<span className="value">{formatNumber(listing?.likeCount)}</span>
						</div>
					</div>
				</div>
			</div>

			<div className="description" style={{ margin: 0 }}>
				<p>{listing.description}</p>
			</div>
		</div>
	)

}

const Home: NextPage = () => {
	const messages = api.listings.getMessage.useQuery();
	const listings = api.listings.list.useQuery();

	const router = useRouter();


	useEffect(() => {
		// console.log()
	}, [router])
	return (
		<>
			<Head>
				<title>My Deals | AcquireAI</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="deals-wrapper">
				<div className="flex flex-row chat-wrapper">
					<div className="w-30">
						<h1 className="heading p-6">Your listed products</h1>
						<div className="listed-products-wrapper">
							{listings?.data?.map((listing) => (
								<ListedProduct key={listing.id} listing={listing} />
							))}
						</div>
					</div>

					{router?.query?.chatId &&
						<>
							<div className="w-40">
								
							</div>
							<div className="w-30">

							</div>
						</>
					}

					{!router?.query?.chatId &&
						<>
							<div className="w-70 placeholder-chat-wrapper">
								<img src="./chat-placeholder.svg" alt="" />
								<h1>No chat conversation selected. Please select one conversation to display its content.</h1>
							</div>
						</>
					}
				</div>
			</main>
		</>
	);
};

export default Home;
